
name: Генерация артефактов из Protobuf

on:
  push:
    branches: [ "master" ]
    paths:
    - "auth.proto"

jobs:

  build:

    runs-on: ubuntu-latest
  
    steps:
    
    - name: Выгрузка кода
      uses: actions/checkout@v2
      
    - name: Настройка Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.23.3'
        
    - name: Установка компилятора Protobuf
      run: |
        PB_REL="https://github.com/protocolbuffers/protobuf/releases"
        curl -LO $PB_REL/download/v25.1/protoc-25.1-linux-x86_64.zip
        unzip protoc-25.1-linux-x86_64.zip -d $HOME/.local
        rm protoc-25.1-linux-x86_64.zip
        export PATH="$PATH:$HOME/.local/bin"
        echo 'export PATH="$PATH:$HOME/.local/bin"' >> ~/.bashrc
        source ~/.bashrc
        
    - name: Установка protoc-gen-go
      run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest

    - name: Установка protoc-gen-go-grpc
      run: go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

    - name: Генерация Go-кода
      run: protoc --go_out=. --go-grpc_out=. auth.proto
     
    - name: Проверка наличия сгенерированного файла
      run: ls -la

    - name: Checkout Go module repository
      uses: actions/checkout@v2
      with:
        repository: sandrinasava/go-proto-module
        token: ${{ secrets.PROTO_TOKEN }} 
        path: go-proto-module

    - name: Copy generated files
      run: |
       if [ -f proto/auth.pb.go ]; then
       cp proto/auth.pb.go go-proto-module/
       else
       echo "File proto/auth.pb.go not found!"
       exit 1
       fi

    - name: Commit and push changes
      run: |
       cd go-proto-module
       git config --global user.name 'github-actions[bot]'
       git config --global user.email 'github-actions[bot]@users.noreply.github.com'
       git checkout -b update-protobuf-files || true  # Создаем ветку, если она не существует
       git branch  # Проверяем, что ветка создана
       git add auth.pb.go
       git commit -m "Update generated protobuf files"
       git push origin update-protobuf-files

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.PROTO_TOKEN }}
        commit-message: "Update generated protobuf files"
        title: "Update generated protobuf files"
        body: "This PR updates the generated protobuf files."
        branch: "update-protobuf-files"
        base: "main"
        repository: sandrinasava/go-proto-module
